# Generated by Django 3.2.7 on 2021-09-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_confirm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirm',
        ),
    ]
